import 'dotenv/config';
import { db } from './index.js';
import { users, studentProfiles } from './models/users.js';
import { reviews } from './models/reviews.js';
import { bookingSessions, sessionStudents } from './models/booking-sessions.js';
import { paymentProofs } from './models/payment-proofs.js';
import { invoices } from './models/invoices.js';
import { assignments } from './models/assignments.js';
import { homeworkSubmissions } from './models/homework-submissions.js';
import { tickets } from './models/tickets.js';
import { hallOfFame } from './models/hall-of-fame.js';
import { resources } from './models/resources.js';
import { appSettings } from './models/app-settings.js';
import { hashPassword } from '../utils/auth.js';

// ─── 100+ REALISTIC REVIEWS DATASET ───────────────────────────────────────────

const REVIEWS_DATA: Array<{
  name: string;
  cohort: string;
  rating: number;
  status: 'APPROVED' | 'PENDING' | 'REJECTED';
  content: string;
}> = [
  {
    name: 'Ahmed Mostafa',
    cohort: 'Cambridge A-Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Mr. Mohammed simplified electromagnetic induction and circular motion like no one else. I jumped from a C in mock exams to an A* in the June series! His structured notes and past paper breakdowns are pure gold.',
  },
  {
    name: 'Mariam El-Shenawy',
    cohort: 'Edexcel IGCSE Physics 2024 (Grade 9)',
    rating: 5,
    status: 'APPROVED',
    content: 'The weekly problem-solving masterclasses completely changed how I think about physics. I ended up getting a 9 in Edexcel Physics with a 98% raw score! Highly recommend the 1-on-1 sessions.',
  },
  {
    name: 'Dr. Tarek Fouad (Parent)',
    cohort: 'Class of 2024 Parent',
    rating: 5,
    status: 'APPROVED',
    content: 'As a university professor myself, I deeply appreciate Mr. Mohammed’s pedagogical clarity, deep subject mastery, and rigorous intuition. Both of my sons achieved A* under his direct mentorship.',
  },
  {
    name: 'Youssef El-Husseiny',
    cohort: 'Cambridge AS Level 2024 (A)',
    rating: 5,
    status: 'APPROVED',
    content: 'The past paper classified booklets and detailed step-by-step worked solutions saved my life before the May/June exams. Best physics teacher in Egypt by far without question.',
  },
  {
    name: 'Salma Khaled',
    cohort: 'Oxford AQA A-Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Thermal physics and thermodynamics used to give me endless headaches until Mr. Mohammed broke them down step by step. His dedication and round-the-clock support during exam season are unmatched.',
  },
  {
    name: 'Ziad Nour',
    cohort: 'Cambridge IGCSE 2024 (Grade 9)',
    rating: 5,
    status: 'APPROVED',
    content: 'The interactive 1-on-1 sessions were incredibly productive. Every minute was focused on high-yield exam techniques and tackling the trickiest Paper 4 structured questions.',
  },
  {
    name: 'Farida Abdel-Rahman',
    cohort: 'Edexcel International A2 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Scored an A* in A2 Physics! Mr. Mohammed always emphasized mathematical derivations and understanding formulas from first principles rather than blind memorization.',
  },
  {
    name: 'Eng. Hany Zaghloul (Parent)',
    cohort: 'IGCSE 2024 Parent',
    rating: 5,
    status: 'APPROVED',
    content: 'The academy portal made tracking attendance, homework submissions, and lecture recordings completely seamless. Excellent mentorship, regular feedback, and great transparency.',
  },
  {
    name: 'Laila Mansour',
    cohort: 'Cambridge A-Level 2023 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'I got accepted into Imperial College London for Mechanical Engineering thanks to my A* in Physics. Mr. Mohammed made me fall in love with engineering mechanics and applied physics.',
  },
  {
    name: 'Omar Sherif',
    cohort: 'Cambridge AS Level 2024 (A)',
    rating: 5,
    status: 'APPROVED',
    content: 'Wave theory, diffraction gratings, and superposition were made crystal clear through animations and hands-on demonstrations. The best learning experience I had in high school.',
  },
  {
    name: 'Nouran Badr',
    cohort: 'Edexcel IGCSE 2024 (Grade 9)',
    rating: 5,
    status: 'APPROVED',
    content: 'Mr. Mohammed has an extraordinary ability to make you confident in solving any unseen problem. Got an A* with full marks on Paper 1 MCQs and 95% on Paper 2!',
  },
  {
    name: 'Karim Ezzat',
    cohort: 'Cambridge A2 Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'The nuclear physics and quantum mechanics modules were taught with such depth and excitement. The mock exam marking sessions with examiner-level feedback were eye-opening.',
  },
  {
    name: 'Dina Wagdy (Parent)',
    cohort: 'A-Level 2024 Parent',
    rating: 5,
    status: 'APPROVED',
    content: 'Thank you Mr. Mohammed for your endless patience and encouragement with my daughter. Her confidence soared from the very first month and she achieved her dream score of A*!',
  },
  {
    name: 'Hassan Al-Attar',
    cohort: 'Cambridge IGCSE 2023 (Grade 8)',
    rating: 4,
    status: 'APPROVED',
    content: 'Great session pacing, challenging assignments, and prompt homework feedback. Improved my grades from a 5 to an 8 in just 3 months before final exams.',
  },
  {
    name: 'Malak Soliman',
    cohort: 'Oxford AQA AS 2024 (A)',
    rating: 5,
    status: 'APPROVED',
    content: 'The formula cheat sheets and classified question banks provided in the student portal are the most organized resources I have ever seen in my academic journey.',
  },
  {
    name: 'Mostafa Kamel',
    cohort: 'Cambridge A-Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Mr. Mohammed doesn’t just teach you how to pass the exam; he teaches you to think like a true physicist. Truly worth every single session.',
  },
  {
    name: 'Rana Essam',
    cohort: 'Edexcel A-Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Gravitational and electric fields used to confuse me constantly. One 1-to-1 session with Mr. Mohammed cleared up the vector calculus concepts completely.',
  },
  {
    name: 'Dr. Mona Radwan (Parent)',
    cohort: 'Class of 2025 Parent',
    rating: 5,
    status: 'APPROVED',
    content: 'Very professional platform and teacher. Mr. Mohammed is punctual, caring, and keeps parents informed about every progress milestone through regular updates.',
  },
  {
    name: 'Seif El-Din Tamer',
    cohort: 'Cambridge IGCSE 2024 (Grade 9)',
    rating: 5,
    status: 'APPROVED',
    content: 'Never felt overwhelmed even during crunch time before the exams. The revision marathons and live Q&A roundups gave us the winning edge over everyone else.',
  },
  {
    name: 'Jana Hatem',
    cohort: 'Cambridge AS Level 2024 (A)',
    rating: 5,
    status: 'APPROVED',
    content: 'Physics went from being my most stressful subject to my absolute favorite. Achieved Top in School award for Physics AS Level with 97 percentile!',
  },
  {
    name: 'Ibrahim Sabry',
    cohort: 'Edexcel International A2 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Oscillations, simple harmonic motion, and astrophysics were explained brilliantly. The session recordings were invaluable for revision during study leave.',
  },
  {
    name: 'Yasmine Adel',
    cohort: 'Cambridge IGCSE 2024 (Grade 9)',
    rating: 5,
    status: 'APPROVED',
    content: 'Paper 6 Alternative to Practical used to be my biggest weakness. Mr. Mohammed walked us through every experiment setup and graph error calculation method!',
  },
  {
    name: 'Nader El-Gammal (Parent)',
    cohort: 'Cambridge AS Parent',
    rating: 5,
    status: 'APPROVED',
    content: 'The structured approach and digital whiteboard notes provided after every lecture make revising effortless. My son went from struggling at a D to scoring an A.',
  },
  {
    name: 'Sherif El-Banna',
    cohort: 'Cambridge A-Level 2023 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Studying Electrical Circuits and Capacitors with Mr. Mohammed gave me the solid mathematical foundation I needed for Electrical Engineering at TU Munich!',
  },
  {
    name: 'Farah Zaki',
    cohort: 'Oxford AQA A-Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Quantum physics, photoelectric effect, and de Broglie wavelength were explained so clearly with interactive simulations. I scored 100% on unit 4!',
  },
  {
    name: 'Aly Hegazy',
    cohort: 'Cambridge IGCSE 2024 (Grade 9)',
    rating: 5,
    status: 'APPROVED',
    content: 'The classified homework booklets are rigorous and accurately predict what comes up in the real exam papers. Got a 9 easily in June 2024!',
  },
  {
    name: 'Nouran El-Shazly',
    cohort: 'Edexcel AS Level 2024 (A)',
    rating: 5,
    status: 'APPROVED',
    content: 'Mechanics: SUVAT equations, projectile motion, and momentum were made so intuitive. The private 1-on-1 tutoring helped me fix all my conceptual gaps.',
  },
  {
    name: 'Wael El-Kordy (Parent)',
    cohort: 'Class of 2024 Parent',
    rating: 5,
    status: 'APPROVED',
    content: 'Outstanding dedication, top-notch communication, and world-class teaching quality. We couldn’t have asked for a better mentor for our daughter.',
  },
  {
    name: 'Tarek Hamada',
    cohort: 'Cambridge A2 Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Magnetic flux density, Hall effect, and cyclotron particle accelerators made simple! Mr. Mohammed has a gift for making hard physics concepts accessible.',
  },
  {
    name: 'Rana Galal',
    cohort: 'Edexcel IGCSE 2024 (Grade 9)',
    rating: 5,
    status: 'APPROVED',
    content: 'I love how every topic begins with real-world applications before diving into exam questions. It makes learning physics fun, stimulating, and unforgettable.',
  },
  {
    name: 'Kareem Abdel-Meguid',
    cohort: 'Cambridge A-Level 2023 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Now studying Aerospace Engineering at the University of Manchester. The intuition Mr. Mohammed instilled in us regarding fluid dynamics is still helping me today.',
  },
  {
    name: 'Amina El-Mahdy',
    cohort: 'Cambridge AS Level 2024 (A)',
    rating: 5,
    status: 'APPROVED',
    content: 'The homework grading system in this portal with handwritten corrections helped me identify and fix calculation errors before mock exams!',
  },
  {
    name: 'Dr. Sameh Lotfy (Parent)',
    cohort: 'A-Level Parent 2024',
    rating: 5,
    status: 'APPROVED',
    content: 'Mr. Mohammed is not just an instructor; he is an academic counselor who genuinely cares about each student’s future and university prospects.',
  },
  {
    name: 'Zeina Rostom',
    cohort: 'Oxford AQA IGCSE 2024 (Grade 9)',
    rating: 5,
    status: 'APPROVED',
    content: 'I never expected to score 100% on Paper 1! The classified practice banks and timed quizzes prepared us for every tricky question type imaginable.',
  },
  {
    name: 'Adham El-Sayed',
    cohort: 'Cambridge A-Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Nuclear binding energy, mass defect, and radioactive decay equations were demystified completely. Scored an A* with full marks on Paper 4!',
  },
  {
    name: 'Maya Barakat',
    cohort: 'Edexcel A2 Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Thermodynamic cycles, entropy, and black-body radiation were taught with great enthusiasm. You never get bored in Mr. Mohammed’s masterclasses.',
  },
  {
    name: 'Hossam El-Din (Parent)',
    cohort: 'IGCSE Parent 2024',
    rating: 5,
    status: 'APPROVED',
    content: 'Top quality education platform. Top-up and credit booking system is smooth and transparent, and the teacher is always punctual and enthusiastic.',
  },
  {
    name: 'Kenzy Nabil',
    cohort: 'Cambridge AS Level 2024 (A)',
    rating: 5,
    status: 'APPROVED',
    content: 'I was terrifed of Doppler effect and ultrasound acoustic impedance, but Mr. Mohammed’s diagrams and derivations made everything click into place.',
  },
  {
    name: 'Marwan Fayed',
    cohort: 'Cambridge IGCSE 2024 (Grade 9)',
    rating: 5,
    status: 'APPROVED',
    content: 'Hooke’s law, density, and pressure in liquids became second nature. Ended up scoring in the top 1% nationwide in Cambridge Physics!',
  },
  {
    name: 'Hania Kassem',
    cohort: 'Edexcel International A-Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Got accepted into University College London (UCL) for Physics and Astronomy! Mr. Mohammed’s passion for astrophysics inspired me completely.',
  },
  {
    name: 'Hazem El-Shenawy',
    cohort: 'Cambridge A-Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'The revision notes, formula booklets, and live exam solving workshops are the gold standard for British curriculum physics in the Middle East.',
  },
  {
    name: 'Sandra George',
    cohort: 'Cambridge AS Level 2024 (A)',
    rating: 5,
    status: 'APPROVED',
    content: 'Kirchhoff’s laws and potential divider circuits used to be my nightmare. After one targeted private session, I solve circuit problems in under 2 minutes.',
  },
  {
    name: 'Eng. Amr Sallam (Parent)',
    cohort: 'Class of 2024 Parent',
    rating: 5,
    status: 'APPROVED',
    content: 'Excellent support and continuous feedback. Mr. Mohammed makes sure every student reaches their highest potential without unnecessary stress.',
  },
  {
    name: 'Basil El-Kady',
    cohort: 'Edexcel IGCSE 2023 (Grade 9)',
    rating: 5,
    status: 'APPROVED',
    content: 'Light refraction, Snell’s law, total internal reflection, and optical fibres made crystal clear. Scored a 9 with 96% overall score!',
  },
  {
    name: 'Talia Morcos',
    cohort: 'Cambridge A2 Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Capacitors in series and parallel, exponential discharge, and RC time constants were simplified with practical real-world oscilloscope examples.',
  },
  {
    name: 'Rashed Al-Sabah',
    cohort: 'Oxford AQA A-Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Even studying remotely from Kuwait, the online whiteboard interactive system made it feel like I was sitting in a physical 1-on-1 private classroom.',
  },
  {
    name: 'Nouran Kassab',
    cohort: 'Cambridge AS Level 2024 (A)',
    rating: 5,
    status: 'APPROVED',
    content: 'Young’s double slit experiment, monochromatic light interference, and phase difference calculations were explained with unmatched mastery.',
  },
  {
    name: 'Youssef Zaher',
    cohort: 'Edexcel IGCSE 2024 (Grade 9)',
    rating: 4,
    status: 'APPROVED',
    content: 'Challenging problem sets, great weekly feedback, and prompt replies on the support desk. Very organized and high quality.',
  },
  {
    name: 'Ghada El-Baz (Parent)',
    cohort: 'A-Level Parent 2024',
    rating: 5,
    status: 'APPROVED',
    content: 'My son was about to drop physics, but Mr. Mohammed restored his interest and confidence. He ended up scoring an A* and got into AUC Engineering!',
  },
  {
    name: 'Karim Mansour',
    cohort: 'Cambridge A-Level 2023 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Simple harmonic motion, resonance, and damping curves were taught with such mathematical elegance. A master educator in every sense.',
  },
  {
    name: 'Farida Hegazi',
    cohort: 'Cambridge IGCSE 2024 (Grade 9)',
    rating: 5,
    status: 'APPROVED',
    content: 'Electromagnetism, motor effect, Fleming’s left hand rule, and transformers made easy! I used to get confused, now I explain them to my classmates.',
  },
  {
    name: 'Omar El-Alfy',
    cohort: 'Edexcel A2 Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Electric potential, field strength, and Coulomb’s law were broken down with clear vector diagrams that made answering 6-mark questions straightforward.',
  },
  {
    name: 'Salma El-Bitar',
    cohort: 'Oxford AQA AS 2024 (A)',
    rating: 5,
    status: 'APPROVED',
    content: 'The classified homework questions forced us to think deeply rather than just pattern match. Result: 100% on Mechanics unit!',
  },
  {
    name: 'Dr. Mahmoud El-Gohary (Parent)',
    cohort: 'IGCSE Parent 2024',
    rating: 5,
    status: 'APPROVED',
    content: 'Unmatched professionalism and rigorous teaching methodology. The portal makes scheduling and monitoring notes effortless for busy parents.',
  },
  {
    name: 'Ziad El-Touny',
    cohort: 'Cambridge A-Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Standard candle stars, Hubble’s law, and the cosmic microwave background radiation were taught like a thrilling documentary! A* achieved.',
  },
  {
    name: 'Mariam Soliman',
    cohort: 'Edexcel IGCSE 2024 (Grade 9)',
    rating: 5,
    status: 'APPROVED',
    content: 'The live past paper solving sessions right before the May exams were the secret to getting a Grade 9. Best physics teacher ever!',
  },
  {
    name: 'Ahmed El-Shal',
    cohort: 'Cambridge AS Level 2024 (A)',
    rating: 5,
    status: 'APPROVED',
    content: 'Work, energy, power, and kinetic efficiency calculations became effortless after following Mr. Mohammed’s step-by-step framework.',
  },
  {
    name: 'Nadine Ezzat',
    cohort: 'Cambridge A2 Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Ideal gas laws, Boltzmann constant, and root-mean-square speed derivations were made crystal clear. Scored 100% on Paper 4 Section A!',
  },
  {
    name: 'Dr. Ashraf Nabil (Parent)',
    cohort: 'Class of 2024 Parent',
    rating: 5,
    status: 'APPROVED',
    content: 'Our highest recommendations to Mr. Mohammed Sayed. He transformed our daughter’s academic trajectory in physics completely.',
  },
  {
    name: 'Aly Tamer',
    cohort: 'Edexcel A-Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Particle physics: quarks, leptons, baryons, and conservation of strangeness made surprisingly intuitive. Scored an A* easily!',
  },
  {
    name: 'Hania El-Khatib',
    cohort: 'Cambridge IGCSE 2024 (Grade 9)',
    rating: 5,
    status: 'APPROVED',
    content: 'Thermal energy transfers: conduction, convection, radiation, and greenhouse effect explained with memorable practical demonstrations.',
  },
  {
    name: 'Seif El-Bialy',
    cohort: 'Oxford AQA A-Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Magnetic flux linkage, eddy currents, and induction cookers explained from Faraday’s law. Best physics academy in the region.',
  },
  {
    name: 'Laila Rostom',
    cohort: 'Cambridge AS Level 2024 (A)',
    rating: 5,
    status: 'APPROVED',
    content: 'The past paper marathons during Ramadan and spring break were the deciding factor in achieving my Grade A. Thank you Mr. Mohammed!',
  },
  {
    name: 'Mostafa El-Ghazaly',
    cohort: 'Cambridge A-Level 2023 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Now at the University of Edinburgh studying Civil Engineering. The mechanics foundation I built here is still serving me at university.',
  },
  {
    name: 'Dina El-Attar (Parent)',
    cohort: 'IGCSE Parent 2024',
    rating: 5,
    status: 'APPROVED',
    content: 'The academy staff and Mr. Mohammed are always responsive, warm, and highly organized. My son got a 9 in Edexcel Physics!',
  },
  {
    name: 'Kenzy Hegazy',
    cohort: 'Edexcel IGCSE 2024 (Grade 9)',
    rating: 5,
    status: 'APPROVED',
    content: 'Specific heat capacity and latent heat calculations were so clear. The homework feedback pointed out all significant figure mistakes.',
  },
  {
    name: 'Yahya Mansour',
    cohort: 'Cambridge A2 Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Gravitational fields: Newton’s law of gravitation, Kepler’s third law, and geostationary orbits derived and mastered step by step.',
  },
  {
    name: 'Maya Nabil',
    cohort: 'Cambridge AS Level 2024 (A)',
    rating: 5,
    status: 'APPROVED',
    content: 'Stationary waves on a string and in air pipes made simple with visual animations. I got full marks on unit 2 waves section!',
  },
  {
    name: 'Tarek Radwan',
    cohort: 'Oxford AQA A-Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'The 1-on-1 private lessons allowed us to deep dive into past Cambridge papers dating back 15 years. No exam question was unfamiliar!',
  },
  {
    name: 'Reem El-Sayed',
    cohort: 'Cambridge IGCSE 2024 (Grade 9)',
    rating: 5,
    status: 'APPROVED',
    content: 'Radioactivity: alpha, beta, gamma decay properties and half-life decay curves explained with great clarity. Scored an A*!',
  },
  {
    name: 'Sherif El-Naggar',
    cohort: 'Edexcel A-Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Lenz’s law and electromagnetic braking derivations were broken down thoroughly. Best tutor in Cairo for advanced physics.',
  },
  {
    name: 'Dr. Khaled El-Maghraby (Parent)',
    cohort: 'A-Level Parent 2024',
    rating: 5,
    status: 'APPROVED',
    content: 'Superb pedagogical talent. Mr. Mohammed inspires a deep curiosity for science in his students while maintaining high exam discipline.',
  },
  {
    name: 'Jana El-Kordy',
    cohort: 'Cambridge AS Level 2024 (A)',
    rating: 5,
    status: 'APPROVED',
    content: 'Stress, strain, Young modulus, and elastic strain energy calculations became my strongest section on Paper 2!',
  },
  {
    name: 'Marwan El-Shamy',
    cohort: 'Cambridge A-Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Piezoelectric transducers and ultrasound pulse-echo scanning explained for medical physics applications. A* achieved.',
  },
  {
    name: 'Hania Rostom',
    cohort: 'Edexcel IGCSE 2024 (Grade 9)',
    rating: 5,
    status: 'APPROVED',
    content: 'Newton’s three laws of motion, resultant force, and momentum conservation mastered with fun everyday examples.',
  },
  {
    name: 'Karim El-Sayed',
    cohort: 'Oxford AQA IGCSE 2024 (Grade 9)',
    rating: 4,
    status: 'APPROVED',
    content: 'Great masterclasses, comprehensive notes, and challenging mock exams that simulated the real testing environment accurately.',
  },
  {
    name: 'Zeina El-Gammal',
    cohort: 'Cambridge A2 Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Quantum physics, line emission spectra, and photoelectric threshold frequency explained with mathematical rigor. Loved every class!',
  },
  {
    name: 'Nour El-Deen Zaki',
    cohort: 'Cambridge AS Level 2024 (A)',
    rating: 5,
    status: 'APPROVED',
    content: 'Internal resistance and electromotive force equations made clear with graphical gradient interpretations on the digital whiteboard.',
  },
  {
    name: 'Eng. Hisham Fathy (Parent)',
    cohort: 'Class of 2024 Parent',
    rating: 5,
    status: 'APPROVED',
    content: 'From D to A*! The transformation in my son’s academic results and self-belief is extraordinary. Thank you Mr. Mohammed Sayed.',
  },
  {
    name: 'Adham Nabil',
    cohort: 'Edexcel A-Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Nuclear fusion in stellar cores, Hertzsprung-Russell diagrams, and black hole event horizons were fascinating topics to learn.',
  },
  {
    name: 'Tia Barakat',
    cohort: 'Cambridge IGCSE 2024 (Grade 9)',
    rating: 5,
    status: 'APPROVED',
    content: 'Electric charge, current, potential difference, and Ohm’s law mastered through problem solving drills. Scored 98%!',
  },
  {
    name: 'Sandra Fayed',
    cohort: 'Cambridge AS Level 2024 (A)',
    rating: 5,
    status: 'APPROVED',
    content: 'Moment of a force, principle of moments, and center of gravity calculations explained with step-by-step vector balance rules.',
  },
  {
    name: 'Hamza El-Kady',
    cohort: 'Cambridge A-Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Alternating currents: root-mean-square voltage, rectification with diodes, and smoothing capacitors made effortless to solve.',
  },
  {
    name: 'Mona El-Shenawy (Parent)',
    cohort: 'IGCSE Parent 2024',
    rating: 5,
    status: 'APPROVED',
    content: 'Great attention to detail, highly supportive instructor, and regular homework tracking. My daughter scored Grade 9 with distinction!',
  },
  {
    name: 'Basil Zaher',
    cohort: 'Edexcel International A2 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Gravitational potential energy at infinity and escape velocity derivations were demystified. I scored 99% raw on Unit 5.',
  },
  {
    name: 'Talia Hegazy',
    cohort: 'Oxford AQA A-Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Thermodynamics first law, isobaric and isothermal processes were taught with p-V work graphs that eliminated all confusion.',
  },
  {
    name: 'Rashed Mansour',
    cohort: 'Cambridge IGCSE 2024 (Grade 9)',
    rating: 5,
    status: 'APPROVED',
    content: 'Sound waves, echo calculations, ultrasound, and human hearing range explained with audio demonstrations in class!',
  },
  {
    name: 'Nouran Fathy',
    cohort: 'Cambridge AS Level 2024 (A)',
    rating: 5,
    status: 'APPROVED',
    content: 'Polarization of transverse waves, Malus’s law, and Brewster angle made clear with polarizing filter animations!',
  },
  {
    name: 'Youssef El-Shal',
    cohort: 'Edexcel IGCSE 2024 (Grade 9)',
    rating: 5,
    status: 'APPROVED',
    content: 'Kinetic theory of matter and Brownian motion explained thoroughly. Top marks on all past paper questions!',
  },
  {
    name: 'Farida Morcos',
    cohort: 'Cambridge A-Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'X-ray production, attenuation coefficient, and CT scanning physics made so clear for medical physics modules. A* achieved.',
  },
  {
    name: 'Dr. Yasser Kassab (Parent)',
    cohort: 'A-Level Parent 2024',
    rating: 5,
    status: 'APPROVED',
    content: 'Mr. Mohammed has an exceptional talent for unlocking student potential and inspiring scientific passion. My son scored an A* in A2.',
  },
  {
    name: 'Omar Nabil',
    cohort: 'Oxford AQA IGCSE 2024 (Grade 9)',
    rating: 5,
    status: 'APPROVED',
    content: 'Velocity-time graphs, area under graph, and acceleration gradients became second nature. Got a 9 in Oxford AQA Physics!',
  },
  {
    name: 'Salma El-Khatib',
    cohort: 'Cambridge AS Level 2024 (A)',
    rating: 5,
    status: 'APPROVED',
    content: 'Projectile motion independence of horizontal and vertical vectors drilled until I could solve any projectile problem blindfolded.',
  },
  {
    name: 'Karim Fayed',
    cohort: 'Cambridge A2 Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Magnetic resonance imaging (MRI), Larmor precession frequency, and RF pulses taught with incredible clarity. A* achieved!',
  },
  {
    name: 'Malak El-Sayed',
    cohort: 'Edexcel IGCSE 2024 (Grade 9)',
    rating: 5,
    status: 'APPROVED',
    content: 'Energy resources: wind, hydroelectric, solar, nuclear, and geothermal energy transfers and efficiency equations mastered!',
  },
  {
    name: 'Ziad Barakat',
    cohort: 'Cambridge A-Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Special relativity time dilation and length contraction explained with Minkowski spacetime diagrams. Super fun and rewarding class.',
  },
  {
    name: 'Mariam Hegazy',
    cohort: 'Cambridge AS Level 2024 (A)',
    rating: 5,
    status: 'APPROVED',
    content: 'Current electricity resistivity formula and temperature coefficient of resistance explained with practical thermistor circuits.',
  },
  {
    name: 'Hossam Nabil (Parent)',
    cohort: 'Class of 2024 Parent',
    rating: 5,
    status: 'APPROVED',
    content: 'Wonderful teacher and top educational environment. My daughter loved every session and gained true confidence in problem solving.',
  },
  {
    name: 'Kenzy Mansour',
    cohort: 'Oxford AQA A-Level 2024 (A*)',
    rating: 5,
    status: 'APPROVED',
    content: 'Thermodynamic entropy changes and second law of thermodynamics explained with statistical microstates. Truly university level insight!',
  },
  {
    name: 'Ahmed El-Gammal',
    cohort: 'Edexcel IGCSE 2024 (Grade 9)',
    rating: 5,
    status: 'APPROVED',
    content: 'Centripetal force, circular orbits, and satellite speed calculations mastered. Scored a Grade 9 with 97% overall!',
  },
  // ── Pending reviews for Admin Moderation ──
  {
    name: 'Layla El-Sayed',
    cohort: 'Cambridge IGCSE 2025 (Current Student)',
    rating: 5,
    status: 'PENDING',
    content: 'Just started the Mechanics module and already feel 10x more confident! The session recordings and interactive notes are so helpful for reviewing before school quizzes.',
  },
  {
    name: 'Tarek Mostafa (Parent)',
    cohort: 'Year 11 Parent',
    rating: 5,
    status: 'PENDING',
    content: 'Very pleased with my son’s progress over the past two months. His school grades improved from 65% to 92% in the November midterm tests.',
  },
  {
    name: 'Youssef El-Badry',
    cohort: 'Edexcel A-Level 2025',
    rating: 5,
    status: 'PENDING',
    content: 'The 1-on-1 private tutorials are outstanding. Mr. Mohammed helped me tackle tricky circular motion problems that my school teacher skipped over.',
  },
  {
    name: 'Nouran Helmy',
    cohort: 'Oxford AQA AS 2025',
    rating: 5,
    status: 'PENDING',
    content: 'The classified homework questions and immediate feedback via the student portal make revising so structured and stress-free. 5 stars!',
  },
  {
    name: 'Eng. Magdy Soliman (Parent)',
    cohort: 'Class of 2025 Parent',
    rating: 5,
    status: 'PENDING',
    content: 'Thank you Mr. Mohammed for the dedication and structured approach. The online learning experience is even better than in-person tutoring.',
  },
  // ── Rejected reviews for moderation testing ──
  {
    name: 'Spam Bot Test',
    cohort: 'Spam 2024',
    rating: 1,
    status: 'REJECTED',
    content: 'Buy essay writing services online at cheap discounts visit our website now.',
  },
  {
    name: 'Anonymous Incomplete',
    cohort: 'Unknown',
    rating: 3,
    status: 'REJECTED',
    content: 'Test review submission testing form validation.',
  },
];

// ─── 35+ REALISTIC STUDENTS DATASET ───────────────────────────────────────────

interface StudentSeedData {
  name: string;
  email: string;
  phone: string;
  schoolName: string;
  year: string;
  academicYear: string;
  gradeLevel: string;
  board: string;
  examBoard: string;
  enrolledCourse: string;
  cohort: string;
  parentName: string;
  parentPhone: string;
  parentEmail: string;
  remainingPrivateCredits: number;
  remainingGroupCredits: number;
  attendanceRate: string;
  averageScore: string;
  hardestTopic: string;
  status: 'ACTIVE' | 'Waiting for Activation';
  isAccountGranted: boolean;
  meetingLink: string;
}

const STUDENTS_DATA: StudentSeedData[] = [
  {
    name: 'Omar Tarek',
    email: 'student@example.com',
    phone: '01012345678',
    schoolName: 'Modern English School Cairo (MES)',
    year: 'Year 12 (AS-Level)',
    academicYear: 'Year 12 (AS-Level)',
    gradeLevel: 'Grade 11 - AS Level',
    board: 'Cambridge (0625 / 9702)',
    examBoard: 'Cambridge (0625 / 9702)',
    enrolledCourse: 'Cambridge International AS Physics (9702)',
    cohort: '2025-Quantum-A',
    parentName: 'Tarek Abdel-Aziz',
    parentPhone: '01098765432',
    parentEmail: 'tarek.abdelaziz@example.com',
    remainingPrivateCredits: 6,
    remainingGroupCredits: 8,
    attendanceRate: '96.50',
    averageScore: '92.00',
    hardestTopic: 'Electromagnetic Induction & Lenz’s Law',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-omar',
  },
  {
    name: 'Mariam Mostafa',
    email: 'mariam.mostafa@example.com',
    phone: '01123456789',
    schoolName: 'Cairo American College (CAC)',
    year: 'Year 12 (AS-Level)',
    academicYear: 'Year 12 (AS-Level)',
    gradeLevel: 'Grade 11 - AS Level',
    board: 'Cambridge (0625 / 9702)',
    examBoard: 'Cambridge (0625 / 9702)',
    enrolledCourse: 'Cambridge International AS Physics (9702)',
    cohort: '2025-Quantum-A',
    parentName: 'Dr. Mostafa El-Shenawy',
    parentPhone: '01187654321',
    parentEmail: 'mostafa.shenawy@example.com',
    remainingPrivateCredits: 4,
    remainingGroupCredits: 6,
    attendanceRate: '98.00',
    averageScore: '95.50',
    hardestTopic: 'Superposition & Diffraction Gratings',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-mariam',
  },
  {
    name: 'Ziad Hassan',
    email: 'ziad.hassan@example.com',
    phone: '01234567890',
    schoolName: 'New Cairo British International School (NCBIS)',
    year: 'Year 11 (IGCSE/O-Level)',
    academicYear: 'Year 11 (IGCSE/O-Level)',
    gradeLevel: 'Grade 10 - IGCSE',
    board: 'Edexcel (4PH1 / WPH11)',
    examBoard: 'Edexcel (4PH1 / WPH11)',
    enrolledCourse: 'Edexcel International IGCSE Physics (4PH1)',
    cohort: '2026-IGCSE-Alpha',
    parentName: 'Eng. Hassan Nour',
    parentPhone: '01276543210',
    parentEmail: 'hassan.nour@example.com',
    remainingPrivateCredits: 8,
    remainingGroupCredits: 12,
    attendanceRate: '94.00',
    averageScore: '89.50',
    hardestTopic: 'Specific Heat Capacity & Thermal Transfers',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-ziad',
  },
  {
    name: 'Farida Abdel-Aziz',
    email: 'farida.nour@example.com',
    phone: '01545678901',
    schoolName: 'British International School in Cairo (BISC)',
    year: 'Year 13 (A2-Level)',
    academicYear: 'Year 13 (A2-Level)',
    gradeLevel: 'Grade 12 - A2 Level',
    board: 'Cambridge (0625 / 9702)',
    examBoard: 'Cambridge (0625 / 9702)',
    enrolledCourse: 'Cambridge International A2 Physics (9702)',
    cohort: '2025-Relativity-A2',
    parentName: 'Dr. Abdel-Aziz Radwan',
    parentPhone: '01565432109',
    parentEmail: 'dr.abdelaziz@example.com',
    remainingPrivateCredits: 2,
    remainingGroupCredits: 4,
    attendanceRate: '100.00',
    averageScore: '98.00',
    hardestTopic: 'Gravitational & Electric Potentials',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-farida',
  },
  {
    name: 'Youssef Mansour',
    email: 'youssef.mansour@example.com',
    phone: '01056789012',
    schoolName: 'Schutz American School Alexandria',
    year: 'Year 12 (AS-Level)',
    academicYear: 'Year 12 (AS-Level)',
    gradeLevel: 'Grade 11 - AS Level',
    board: 'Oxford AQA (9630 / 9631)',
    examBoard: 'Oxford AQA (9630 / 9631)',
    enrolledCourse: 'Oxford AQA International AS Physics (9630)',
    cohort: '2025-Newtonian-AS',
    parentName: 'Mansour El-Kady',
    parentPhone: '01043210987',
    parentEmail: 'mansour.kady@example.com',
    remainingPrivateCredits: 5,
    remainingGroupCredits: 10,
    attendanceRate: '92.50',
    averageScore: '88.00',
    hardestTopic: 'Projectile Motion & Momentum in 2D',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-youssef',
  },
  {
    name: 'Salma El-Ghazaly',
    email: 'salma.ghazaly@example.com',
    phone: '01167890123',
    schoolName: 'El Alsson British & American International School',
    year: 'Year 11 (IGCSE/O-Level)',
    academicYear: 'Year 11 (IGCSE/O-Level)',
    gradeLevel: 'Grade 10 - IGCSE',
    board: 'Cambridge (0625 / 9702)',
    examBoard: 'Cambridge (0625 / 9702)',
    enrolledCourse: 'Cambridge IGCSE Physics (0625)',
    cohort: '2026-IGCSE-Beta',
    parentName: 'Amr El-Ghazaly',
    parentPhone: '01132109876',
    parentEmail: 'amr.ghazaly@example.com',
    remainingPrivateCredits: 3,
    remainingGroupCredits: 6,
    attendanceRate: '95.00',
    averageScore: '91.00',
    hardestTopic: 'Paper 6 Alternative to Practical Lab Design',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-salma',
  },
  {
    name: 'Karim Sherif',
    email: 'karim.sherif@example.com',
    phone: '01278901234',
    schoolName: 'Manor House International School',
    year: 'Year 13 (A2-Level)',
    academicYear: 'Year 13 (A2-Level)',
    gradeLevel: 'Grade 12 - A2 Level',
    board: 'Edexcel (4PH1 / WPH11)',
    examBoard: 'Edexcel (4PH1 / WPH11)',
    enrolledCourse: 'Edexcel International A2 Physics (WPH12)',
    cohort: '2025-Relativity-A2',
    parentName: 'Sherif Zaghloul',
    parentPhone: '01221098765',
    parentEmail: 'sherif.zaghloul@example.com',
    remainingPrivateCredits: 7,
    remainingGroupCredits: 8,
    attendanceRate: '97.00',
    averageScore: '94.00',
    hardestTopic: 'Nuclear Binding Energy & Fission',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-karim',
  },
  {
    name: 'Malak Zaher',
    email: 'malak.zaher@example.com',
    phone: '01589012345',
    schoolName: 'American International School in Egypt (AIS)',
    year: 'Year 10 (IGCSE)',
    academicYear: 'Year 10 (IGCSE)',
    gradeLevel: 'Grade 9 - IGCSE Foundations',
    board: 'Cambridge (0625 / 9702)',
    examBoard: 'Cambridge (0625 / 9702)',
    enrolledCourse: 'Cambridge IGCSE Physics (0625)',
    cohort: '2026-IGCSE-Alpha',
    parentName: 'Zaher Rostom',
    parentPhone: '01510987654',
    parentEmail: 'zaher.rostom@example.com',
    remainingPrivateCredits: 10,
    remainingGroupCredits: 14,
    attendanceRate: '99.00',
    averageScore: '96.00',
    hardestTopic: 'Density & Liquid Pressure Calculations',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-malak',
  },
  {
    name: 'Ahmed Helmy',
    email: 'ahmed.helmy@example.com',
    phone: '01090123456',
    schoolName: 'Hayah International Academy',
    year: 'Year 12 (AS-Level)',
    academicYear: 'Year 12 (AS-Level)',
    gradeLevel: 'Grade 11 - AS Level',
    board: 'Cambridge (0625 / 9702)',
    examBoard: 'Cambridge (0625 / 9702)',
    enrolledCourse: 'Cambridge International AS Physics (9702)',
    cohort: '2025-Quantum-B',
    parentName: 'Dr. Helmy Fathy',
    parentPhone: '01009876543',
    parentEmail: 'helmy.fathy@example.com',
    remainingPrivateCredits: 4,
    remainingGroupCredits: 6,
    attendanceRate: '91.00',
    averageScore: '86.50',
    hardestTopic: 'Kirchhoff’s Loop Rules in DC Circuits',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-ahmed',
  },
  {
    name: 'Jana El-Shenawy',
    email: 'jana.shenawy@example.com',
    phone: '01101234567',
    schoolName: 'Victoria College Alexandria',
    year: 'Year 11 (IGCSE/O-Level)',
    academicYear: 'Year 11 (IGCSE/O-Level)',
    gradeLevel: 'Grade 10 - IGCSE',
    board: 'Edexcel (4PH1 / WPH11)',
    examBoard: 'Edexcel (4PH1 / WPH11)',
    enrolledCourse: 'Edexcel International IGCSE Physics (4PH1)',
    cohort: '2026-IGCSE-Beta',
    parentName: 'Eng. Hatem Shenawy',
    parentPhone: '01198765430',
    parentEmail: 'hatem.shenawy@example.com',
    remainingPrivateCredits: 6,
    remainingGroupCredits: 8,
    attendanceRate: '97.50',
    averageScore: '93.50',
    hardestTopic: 'Electromagnetic Spectrum & Wave Speed',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-jana',
  },
  {
    name: 'Seif El-Deen Tamer',
    email: 'seif.eldeen@example.com',
    phone: '01212345678',
    schoolName: 'Cairo American College (CAC)',
    year: 'Year 13 (A2-Level)',
    academicYear: 'Year 13 (A2-Level)',
    gradeLevel: 'Grade 12 - A2 Level',
    board: 'Cambridge (0625 / 9702)',
    examBoard: 'Cambridge (0625 / 9702)',
    enrolledCourse: 'Cambridge International A2 Physics (9702)',
    cohort: '2025-Relativity-A2',
    parentName: 'Tamer Galal',
    parentPhone: '01287654320',
    parentEmail: 'tamer.galal@example.com',
    remainingPrivateCredits: 8,
    remainingGroupCredits: 10,
    attendanceRate: '98.50',
    averageScore: '97.00',
    hardestTopic: 'Capacitor Exponential Discharge Formula',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-seif',
  },
  {
    name: 'Hania Badr',
    email: 'hania.badr@example.com',
    phone: '01523456789',
    schoolName: 'Modern English School Cairo (MES)',
    year: 'Year 12 (AS-Level)',
    academicYear: 'Year 12 (AS-Level)',
    gradeLevel: 'Grade 11 - AS Level',
    board: 'Oxford AQA (9630 / 9631)',
    examBoard: 'Oxford AQA (9630 / 9631)',
    enrolledCourse: 'Oxford AQA International AS Physics (9630)',
    cohort: '2025-Newtonian-AS',
    parentName: 'Badr El-Mahdy',
    parentPhone: '01576543210',
    parentEmail: 'badr.mahdy@example.com',
    remainingPrivateCredits: 2,
    remainingGroupCredits: 4,
    attendanceRate: '93.00',
    averageScore: '89.00',
    hardestTopic: 'Stationary Waves & Node Positions',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-hania',
  },
  {
    name: 'Mostafa Kamel',
    email: 'mostafa.kamel@example.com',
    phone: '01034567891',
    schoolName: 'Schutz American School Alexandria',
    year: 'Year 11 (IGCSE/O-Level)',
    academicYear: 'Year 11 (IGCSE/O-Level)',
    gradeLevel: 'Grade 10 - IGCSE',
    board: 'Cambridge (0625 / 9702)',
    examBoard: 'Cambridge (0625 / 9702)',
    enrolledCourse: 'Cambridge IGCSE Physics (0625)',
    cohort: '2026-IGCSE-Alpha',
    parentName: 'Kamel Lotfy',
    parentPhone: '01065432108',
    parentEmail: 'kamel.lotfy@example.com',
    remainingPrivateCredits: 5,
    remainingGroupCredits: 12,
    attendanceRate: '96.00',
    averageScore: '92.50',
    hardestTopic: 'Electric Circuits & Ohm’s Law',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-mostafa',
  },
  {
    name: 'Dina Fathy',
    email: 'dina.fathy@example.com',
    phone: '01145678902',
    schoolName: 'British International School in Cairo (BISC)',
    year: 'Year 12 (AS-Level)',
    academicYear: 'Year 12 (AS-Level)',
    gradeLevel: 'Grade 11 - AS Level',
    board: 'Cambridge (0625 / 9702)',
    examBoard: 'Cambridge (0625 / 9702)',
    enrolledCourse: 'Cambridge International AS Physics (9702)',
    cohort: '2025-Quantum-A',
    parentName: 'Fathy El-Kordy',
    parentPhone: '01154321097',
    parentEmail: 'fathy.kordy@example.com',
    remainingPrivateCredits: 4,
    remainingGroupCredits: 6,
    attendanceRate: '99.00',
    averageScore: '96.50',
    hardestTopic: 'Photoelectric Effect Threshold Frequency',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-dina',
  },
  {
    name: 'Aly Ezzat',
    email: 'aly.ezzat@example.com',
    phone: '01256789013',
    schoolName: 'New Cairo British International School (NCBIS)',
    year: 'Year 13 (A2-Level)',
    academicYear: 'Year 13 (A2-Level)',
    gradeLevel: 'Grade 12 - A2 Level',
    board: 'Edexcel (4PH1 / WPH11)',
    examBoard: 'Edexcel (4PH1 / WPH11)',
    enrolledCourse: 'Edexcel International A2 Physics (WPH12)',
    cohort: '2025-Relativity-A2',
    parentName: 'Dr. Ezzat Nabil',
    parentPhone: '01243210986',
    parentEmail: 'ezzat.nabil@example.com',
    remainingPrivateCredits: 3,
    remainingGroupCredits: 8,
    attendanceRate: '95.50',
    averageScore: '93.00',
    hardestTopic: 'Simple Harmonic Motion Phase Angle',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-aly',
  },
  {
    name: 'Zeina Nabil',
    email: 'zeina.nabil@example.com',
    phone: '01567890124',
    schoolName: 'El Alsson British & American International School',
    year: 'Year 10 (IGCSE)',
    academicYear: 'Year 10 (IGCSE)',
    gradeLevel: 'Grade 9 - IGCSE Foundations',
    board: 'Cambridge (0625 / 9702)',
    examBoard: 'Cambridge (0625 / 9702)',
    enrolledCourse: 'Cambridge IGCSE Physics (0625)',
    cohort: '2026-IGCSE-Alpha',
    parentName: 'Nabil Mansour',
    parentPhone: '01532109875',
    parentEmail: 'nabil.mansour@example.com',
    remainingPrivateCredits: 8,
    remainingGroupCredits: 10,
    attendanceRate: '94.50',
    averageScore: '90.00',
    hardestTopic: 'Speed-Time Acceleration Graphs',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-zeina',
  },
  {
    name: 'Tarek El-Kady',
    email: 'tarek.kady@example.com',
    phone: '01078901235',
    schoolName: 'Schutz American School Alexandria',
    year: 'Year 12 (AS-Level)',
    academicYear: 'Year 12 (AS-Level)',
    gradeLevel: 'Grade 11 - AS Level',
    board: 'Cambridge (0625 / 9702)',
    examBoard: 'Cambridge (0625 / 9702)',
    enrolledCourse: 'Cambridge International AS Physics (9702)',
    cohort: '2025-Quantum-B',
    parentName: 'Eng. Amr El-Kady',
    parentPhone: '01021098764',
    parentEmail: 'amr.kady@example.com',
    remainingPrivateCredits: 6,
    remainingGroupCredits: 8,
    attendanceRate: '97.00',
    averageScore: '94.50',
    hardestTopic: 'Doppler Effect Acoustic Shift',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-tarek',
  },
  {
    name: 'Reem Hegazy',
    email: 'reem.hegazy@example.com',
    phone: '01189012346',
    schoolName: 'American International School (AIS West)',
    year: 'Year 11 (IGCSE/O-Level)',
    academicYear: 'Year 11 (IGCSE/O-Level)',
    gradeLevel: 'Grade 10 - IGCSE',
    board: 'Edexcel (4PH1 / WPH11)',
    examBoard: 'Edexcel (4PH1 / WPH11)',
    enrolledCourse: 'Edexcel International IGCSE Physics (4PH1)',
    cohort: '2026-IGCSE-Beta',
    parentName: 'Dr. Hegazy El-Sayed',
    parentPhone: '01110987653',
    parentEmail: 'hegazy.sayed@example.com',
    remainingPrivateCredits: 4,
    remainingGroupCredits: 6,
    attendanceRate: '98.00',
    averageScore: '95.00',
    hardestTopic: 'Nuclear Half-Life Decay Calculations',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-reem',
  },
  {
    name: 'Yahya Sallam',
    email: 'yahya.sallam@example.com',
    phone: '01290123457',
    schoolName: 'Manor House International School',
    year: 'Year 13 (A2-Level)',
    academicYear: 'Year 13 (A2-Level)',
    gradeLevel: 'Grade 12 - A2 Level',
    board: 'Cambridge (0625 / 9702)',
    examBoard: 'Cambridge (0625 / 9702)',
    enrolledCourse: 'Cambridge International A2 Physics (9702)',
    cohort: '2025-Relativity-A2',
    parentName: 'Sallam Barakat',
    parentPhone: '01209876542',
    parentEmail: 'sallam.barakat@example.com',
    remainingPrivateCredits: 5,
    remainingGroupCredits: 10,
    attendanceRate: '96.00',
    averageScore: '91.50',
    hardestTopic: 'Thermodynamic Carnot Engines & Work',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-yahya',
  },
  {
    name: 'Nadine Shawky',
    email: 'nadine.shawky@example.com',
    phone: '01501234568',
    schoolName: 'Modern English School Cairo (MES)',
    year: 'Year 12 (AS-Level)',
    academicYear: 'Year 12 (AS-Level)',
    gradeLevel: 'Grade 11 - AS Level',
    board: 'Oxford AQA (9630 / 9631)',
    examBoard: 'Oxford AQA (9630 / 9631)',
    enrolledCourse: 'Oxford AQA International AS Physics (9630)',
    cohort: '2025-Newtonian-AS',
    parentName: 'Shawky Fathy',
    parentPhone: '01598765431',
    parentEmail: 'shawky.fathy@example.com',
    remainingPrivateCredits: 2,
    remainingGroupCredits: 4,
    attendanceRate: '94.00',
    averageScore: '87.50',
    hardestTopic: 'Young Modulus Tensile Stress Graph',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-nadine',
  },
  {
    name: 'Sherif Shawki',
    email: 'sherif.shawki@example.com',
    phone: '01012345679',
    schoolName: 'Cairo American College (CAC)',
    year: 'Year 11 (IGCSE/O-Level)',
    academicYear: 'Year 11 (IGCSE/O-Level)',
    gradeLevel: 'Grade 10 - IGCSE',
    board: 'Cambridge (0625 / 9702)',
    examBoard: 'Cambridge (0625 / 9702)',
    enrolledCourse: 'Cambridge IGCSE Physics (0625)',
    cohort: '2026-IGCSE-Alpha',
    parentName: 'Shawki Mansour',
    parentPhone: '01087654329',
    parentEmail: 'shawki.mansour@example.com',
    remainingPrivateCredits: 6,
    remainingGroupCredits: 12,
    attendanceRate: '98.50',
    averageScore: '96.00',
    hardestTopic: 'Total Internal Reflection & Snell’s Law',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-sherif',
  },
  {
    name: 'Maya Fouad',
    email: 'maya.fouad@example.com',
    phone: '01123456780',
    schoolName: 'Hayah International Academy',
    year: 'Year 12 (AS-Level)',
    academicYear: 'Year 12 (AS-Level)',
    gradeLevel: 'Grade 11 - AS Level',
    board: 'Cambridge (0625 / 9702)',
    examBoard: 'Cambridge (0625 / 9702)',
    enrolledCourse: 'Cambridge International AS Physics (9702)',
    cohort: '2025-Quantum-A',
    parentName: 'Dr. Fouad Zaki',
    parentPhone: '01176543219',
    parentEmail: 'dr.fouad@example.com',
    remainingPrivateCredits: 3,
    remainingGroupCredits: 8,
    attendanceRate: '99.50',
    averageScore: '97.50',
    hardestTopic: 'Diffraction Grating Order Maxima',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-maya',
  },
  {
    name: 'Mahmoud Samir',
    email: 'mahmoud.samir@example.com',
    phone: '01234567891',
    schoolName: 'British International School in Cairo (BISC)',
    year: 'Year 13 (A2-Level)',
    academicYear: 'Year 13 (A2-Level)',
    gradeLevel: 'Grade 12 - A2 Level',
    board: 'Edexcel (4PH1 / WPH11)',
    examBoard: 'Edexcel (4PH1 / WPH11)',
    enrolledCourse: 'Edexcel International A2 Physics (WPH12)',
    cohort: '2025-Relativity-A2',
    parentName: 'Samir Galal',
    parentPhone: '01265432107',
    parentEmail: 'samir.galal@example.com',
    remainingPrivateCredits: 8,
    remainingGroupCredits: 10,
    attendanceRate: '95.00',
    averageScore: '92.00',
    hardestTopic: 'Magnetic Flux Density in Solenoids',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-mahmoud',
  },
  {
    name: 'Judy Soliman',
    email: 'judy.soliman@example.com',
    phone: '01545678902',
    schoolName: 'New Cairo British International School (NCBIS)',
    year: 'Year 10 (IGCSE)',
    academicYear: 'Year 10 (IGCSE)',
    gradeLevel: 'Grade 9 - IGCSE Foundations',
    board: 'Cambridge (0625 / 9702)',
    examBoard: 'Cambridge (0625 / 9702)',
    enrolledCourse: 'Cambridge IGCSE Physics (0625)',
    cohort: '2026-IGCSE-Beta',
    parentName: 'Soliman El-Mahdy',
    parentPhone: '01554321096',
    parentEmail: 'soliman.mahdy@example.com',
    remainingPrivateCredits: 4,
    remainingGroupCredits: 6,
    attendanceRate: '93.50',
    averageScore: '89.00',
    hardestTopic: 'Work Done, Kinetic & GPE Conservation',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-judy',
  },
  {
    name: 'Hazem Wael',
    email: 'hazem.wael@example.com',
    phone: '01056789013',
    schoolName: 'Schutz American School Alexandria',
    year: 'Year 12 (AS-Level)',
    academicYear: 'Year 12 (AS-Level)',
    gradeLevel: 'Grade 11 - AS Level',
    board: 'Cambridge (0625 / 9702)',
    examBoard: 'Cambridge (0625 / 9702)',
    enrolledCourse: 'Cambridge International AS Physics (9702)',
    cohort: '2025-Quantum-B',
    parentName: 'Wael El-Kordy',
    parentPhone: '01043210985',
    parentEmail: 'wael.kordy@example.com',
    remainingPrivateCredits: 7,
    remainingGroupCredits: 8,
    attendanceRate: '97.00',
    averageScore: '94.00',
    hardestTopic: 'De Broglie Wavelength & Particle Nature',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-hazem',
  },
  {
    name: 'Kenzy Erian',
    email: 'kenzy.erian@example.com',
    phone: '01167890124',
    schoolName: 'El Alsson British & American International School',
    year: 'Year 11 (IGCSE/O-Level)',
    academicYear: 'Year 11 (IGCSE/O-Level)',
    gradeLevel: 'Grade 10 - IGCSE',
    board: 'Edexcel (4PH1 / WPH11)',
    examBoard: 'Edexcel (4PH1 / WPH11)',
    enrolledCourse: 'Edexcel International IGCSE Physics (4PH1)',
    cohort: '2026-IGCSE-Alpha',
    parentName: 'Erian Morcos',
    parentPhone: '01132109874',
    parentEmail: 'erian.morcos@example.com',
    remainingPrivateCredits: 5,
    remainingGroupCredits: 10,
    attendanceRate: '96.50',
    averageScore: '93.00',
    hardestTopic: 'Electric Motor & Fleming’s Left Hand Rule',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-kenzy',
  },
  {
    name: 'Marwan Lotfy',
    email: 'marwan.lotfy@example.com',
    phone: '01278901235',
    schoolName: 'American International School (AIS)',
    year: 'Year 13 (A2-Level)',
    academicYear: 'Year 13 (A2-Level)',
    gradeLevel: 'Grade 12 - A2 Level',
    board: 'Cambridge (0625 / 9702)',
    examBoard: 'Cambridge (0625 / 9702)',
    enrolledCourse: 'Cambridge International A2 Physics (9702)',
    cohort: '2025-Relativity-A2',
    parentName: 'Lotfy Hegazy',
    parentPhone: '01221098763',
    parentEmail: 'lotfy.hegazy@example.com',
    remainingPrivateCredits: 6,
    remainingGroupCredits: 6,
    attendanceRate: '98.00',
    averageScore: '95.50',
    hardestTopic: 'Astrophysics & Standard Candle Luminosity',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-marwan',
  },
  {
    name: 'Yasmine Barakat',
    email: 'yasmine.barakat@example.com',
    phone: '01589012346',
    schoolName: 'Modern English School Cairo (MES)',
    year: 'Year 12 (AS-Level)',
    academicYear: 'Year 12 (AS-Level)',
    gradeLevel: 'Grade 11 - AS Level',
    board: 'Oxford AQA (9630 / 9631)',
    examBoard: 'Oxford AQA (9630 / 9631)',
    enrolledCourse: 'Oxford AQA International AS Physics (9630)',
    cohort: '2025-Newtonian-AS',
    parentName: 'Barakat Fathy',
    parentPhone: '01510987652',
    parentEmail: 'barakat.fathy@example.com',
    remainingPrivateCredits: 3,
    remainingGroupCredits: 6,
    attendanceRate: '95.00',
    averageScore: '90.50',
    hardestTopic: 'Moments of Forces & Center of Gravity',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-yasmine',
  },
  {
    name: 'Adham Gamal',
    email: 'adham.gamal@example.com',
    phone: '01090123457',
    schoolName: 'Victoria College Alexandria',
    year: 'Year 11 (IGCSE/O-Level)',
    academicYear: 'Year 11 (IGCSE/O-Level)',
    gradeLevel: 'Grade 10 - IGCSE',
    board: 'Cambridge (0625 / 9702)',
    examBoard: 'Cambridge (0625 / 9702)',
    enrolledCourse: 'Cambridge IGCSE Physics (0625)',
    cohort: '2026-IGCSE-Beta',
    parentName: 'Gamal El-Attar',
    parentPhone: '01009876541',
    parentEmail: 'gamal.attar@example.com',
    remainingPrivateCredits: 5,
    remainingGroupCredits: 8,
    attendanceRate: '94.00',
    averageScore: '88.50',
    hardestTopic: 'Pressure Differences in Manometers',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-adham',
  },
  {
    name: 'Tia Rostom',
    email: 'tia.rostom@example.com',
    phone: '01101234568',
    schoolName: 'Cairo American College (CAC)',
    year: 'Year 12 (AS-Level)',
    academicYear: 'Year 12 (AS-Level)',
    gradeLevel: 'Grade 11 - AS Level',
    board: 'Cambridge (0625 / 9702)',
    examBoard: 'Cambridge (0625 / 9702)',
    enrolledCourse: 'Cambridge International AS Physics (9702)',
    cohort: '2025-Quantum-A',
    parentName: 'Rostom Galal',
    parentPhone: '01198765429',
    parentEmail: 'rostom.galal@example.com',
    remainingPrivateCredits: 7,
    remainingGroupCredits: 10,
    attendanceRate: '100.00',
    averageScore: '98.50',
    hardestTopic: 'Electric Field Strength Vector Superposition',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-tia',
  },
  {
    name: 'Basil El-Gammal',
    email: 'basil.gammal@example.com',
    phone: '01212345679',
    schoolName: 'British International School in Cairo (BISC)',
    year: 'Year 13 (A2-Level)',
    academicYear: 'Year 13 (A2-Level)',
    gradeLevel: 'Grade 12 - A2 Level',
    board: 'Edexcel (4PH1 / WPH11)',
    examBoard: 'Edexcel (4PH1 / WPH11)',
    enrolledCourse: 'Edexcel International A2 Physics (WPH12)',
    cohort: '2025-Relativity-A2',
    parentName: 'Dr. Gammal Nabil',
    parentPhone: '01287654319',
    parentEmail: 'dr.gammal@example.com',
    remainingPrivateCredits: 4,
    remainingGroupCredits: 6,
    attendanceRate: '96.00',
    averageScore: '93.00',
    hardestTopic: 'Resonance in Driven Oscillations',
    status: 'ACTIVE',
    isAccountGranted: true,
    meetingLink: 'https://meet.google.com/sayed-physics-basil',
  },
  // ── Onboarding / Waiting for Activation Queue Students ──
  {
    name: 'Sandra George',
    email: 'sandra.george@example.com',
    phone: '01523456780',
    schoolName: 'Manor House International School',
    year: 'Year 11 (IGCSE/O-Level)',
    academicYear: 'Year 11 (IGCSE/O-Level)',
    gradeLevel: 'Grade 10 - IGCSE',
    board: 'Cambridge (0625 / 9702)',
    examBoard: 'Cambridge (0625 / 9702)',
    enrolledCourse: 'Cambridge IGCSE Physics (0625)',
    cohort: '2026-IGCSE-Beta',
    parentName: 'George Fayed',
    parentPhone: '01576543209',
    parentEmail: 'george.fayed@example.com',
    remainingPrivateCredits: 0,
    remainingGroupCredits: 0,
    attendanceRate: '0.00',
    averageScore: '0.00',
    hardestTopic: 'Electromagnetism',
    status: 'Waiting for Activation',
    isAccountGranted: false,
    meetingLink: '',
  },
  {
    name: 'Hamza El-Sayed',
    email: 'hamza.elsayed@example.com',
    phone: '01034567892',
    schoolName: 'Hayah International Academy',
    year: 'Year 10 (IGCSE)',
    academicYear: 'Year 10 (IGCSE)',
    gradeLevel: 'Grade 9 - IGCSE Foundations',
    board: 'Edexcel (4PH1 / WPH11)',
    examBoard: 'Edexcel (4PH1 / WPH11)',
    enrolledCourse: 'Edexcel International IGCSE Physics (4PH1)',
    cohort: '2026-IGCSE-Alpha',
    parentName: 'Sayed Lotfy',
    parentPhone: '01065432107',
    parentEmail: 'sayed.lotfy@example.com',
    remainingPrivateCredits: 0,
    remainingGroupCredits: 0,
    attendanceRate: '0.00',
    averageScore: '0.00',
    hardestTopic: 'Vectors and Velocity',
    status: 'Waiting for Activation',
    isAccountGranted: false,
    meetingLink: '',
  },
  {
    name: 'Talia Morcos',
    email: 'talia.morcos@example.com',
    phone: '01145678903',
    schoolName: 'New Cairo British International School (NCBIS)',
    year: 'Year 12 (AS-Level)',
    academicYear: 'Year 12 (AS-Level)',
    gradeLevel: 'Grade 11 - AS Level',
    board: 'Cambridge (0625 / 9702)',
    examBoard: 'Cambridge (0625 / 9702)',
    enrolledCourse: 'Cambridge International AS Physics (9702)',
    cohort: '2025-Quantum-A',
    parentName: 'Morcos Hegazy',
    parentPhone: '01154321096',
    parentEmail: 'morcos.hegazy@example.com',
    remainingPrivateCredits: 0,
    remainingGroupCredits: 0,
    attendanceRate: '0.00',
    averageScore: '0.00',
    hardestTopic: 'Thermal Physics',
    status: 'Waiting for Activation',
    isAccountGranted: false,
    meetingLink: '',
  },
  {
    name: 'Rashed Al-Sabah',
    email: 'rashed.alsabah@example.com',
    phone: '01256789014',
    schoolName: 'Schutz American School Alexandria',
    year: 'Year 11 (IGCSE/O-Level)',
    academicYear: 'Year 11 (IGCSE/O-Level)',
    gradeLevel: 'Grade 10 - IGCSE',
    board: 'Oxford AQA (9630 / 9631)',
    examBoard: 'Oxford AQA (9630 / 9631)',
    enrolledCourse: 'Oxford AQA International IGCSE Physics',
    cohort: '2026-IGCSE-Alpha',
    parentName: 'Al-Sabah Mansour',
    parentPhone: '01243210985',
    parentEmail: 'sabah.mansour@example.com',
    remainingPrivateCredits: 0,
    remainingGroupCredits: 0,
    attendanceRate: '0.00',
    averageScore: '0.00',
    hardestTopic: 'Wave optics',
    status: 'Waiting for Activation',
    isAccountGranted: false,
    meetingLink: '',
  },
  {
    name: 'Nouran Kassab',
    email: 'nouran.kassab@example.com',
    phone: '01567890125',
    schoolName: 'El Alsson British & American International School',
    year: 'Year 13 (A2-Level)',
    academicYear: 'Year 13 (A2-Level)',
    gradeLevel: 'Grade 12 - A2 Level',
    board: 'Cambridge (0625 / 9702)',
    examBoard: 'Cambridge (0625 / 9702)',
    enrolledCourse: 'Cambridge International A2 Physics (9702)',
    cohort: '2025-Relativity-A2',
    parentName: 'Dr. Kassab Zaki',
    parentPhone: '01532109874',
    parentEmail: 'dr.kassab@example.com',
    remainingPrivateCredits: 0,
    remainingGroupCredits: 0,
    attendanceRate: '0.00',
    averageScore: '0.00',
    hardestTopic: 'Quantum Mechanics',
    status: 'Waiting for Activation',
    isAccountGranted: false,
    meetingLink: '',
  },
];

// ─── MAIN SEED RUNNER ─────────────────────────────────────────────────────────

export const runFullSeed = async () => {
  console.log('🚀 Starting comprehensive Physics Academy database seed...');

  // 1. App Settings
  console.log('⚙️ Seeding App Settings...');
  await db.insert(appSettings).values({
    id: 1,
    introVideoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    curriculaOptions: [
      { id: 'cambridge-igcse', label: 'Cambridge IGCSE (0625)', board: 'Cambridge' },
      { id: 'cambridge-as', label: 'Cambridge AS-Level (9702)', board: 'Cambridge' },
      { id: 'cambridge-a2', label: 'Cambridge A2-Level (9702)', board: 'Cambridge' },
      { id: 'edexcel-igcse', label: 'Edexcel International IGCSE (4PH1)', board: 'Edexcel' },
      { id: 'edexcel-ial', label: 'Edexcel International A-Level (WPH11/12)', board: 'Edexcel' },
      { id: 'oxford-aqa', label: 'Oxford AQA International A-Level (9630)', board: 'Oxford AQA' },
    ],
    examSessionOptions: ['May/June 2025', 'Oct/Nov 2025', 'Jan 2026', 'May/June 2026'],
    sessionPricing: {
      private1to1: { pricePerSession: 600, currency: 'EGP', bundleDiscount10x: 5400 },
      groupCohort: { pricePerSession: 300, currency: 'EGP', bundleDiscount10x: 2700 },
    },
  }).onConflictDoUpdate({
    target: appSettings.id,
    set: {
      introVideoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      updatedAt: new Date(),
    },
  });

  // 2. Admin User
  console.log('👤 Seeding Admin User...');
  const defaultPassword = await hashPassword('password123');
  const adminPassword = await hashPassword(process.env.SEED_ADMIN_PASSWORD || 'change-me-admin');

  const [adminUser] = await db.insert(users).values({
    name: 'Mr. Mohammed Sayed',
    email: process.env.SEED_ADMIN_EMAIL || 'admin@example.com',
    password: adminPassword,
    phone: '+20 100 248 5651',
    role: 'ADMIN',
    specialty: 'Lead Master Physics Educator & Curriculum Director',
    status: 'ACTIVE',
  }).onConflictDoUpdate({
    target: users.email,
    set: {
      name: 'Mr. Mohammed Sayed',
      role: 'ADMIN',
      specialty: 'Lead Master Physics Educator & Curriculum Director',
      status: 'ACTIVE',
      updatedAt: new Date(),
    },
  }).returning();

  // 3. Students & Profiles
  console.log('🎓 Seeding 35+ Scholars and Profiles...');
  const createdStudents: Array<{ id: number; name: string; email: string; cohort?: string }> = [];

  for (const s of STUDENTS_DATA) {
    const studentPass = s.email === 'student@example.com' && process.env.SEED_STUDENT_PASSWORD
      ? await hashPassword(process.env.SEED_STUDENT_PASSWORD)
      : defaultPassword;

    const [u] = await db.insert(users).values({
      name: s.name,
      email: s.email,
      password: studentPass,
      phone: s.phone,
      role: 'STUDENT',
      status: s.status,
    }).onConflictDoUpdate({
      target: users.email,
      set: {
        name: s.name,
        phone: s.phone,
        status: s.status,
        updatedAt: new Date(),
      },
    }).returning();

    if (u) {
      createdStudents.push({ id: u.id, name: u.name, email: u.email, cohort: s.cohort });

      await db.insert(studentProfiles).values({
        userId: u.id,
        parentName: s.parentName,
        parentPhone: s.parentPhone,
        parentEmail: s.parentEmail,
        gradeLevel: s.gradeLevel,
        cohort: s.cohort,
        schoolName: s.schoolName,
        year: s.year,
        academicYear: s.academicYear,
        board: s.board,
        examBoard: s.examBoard,
        studentPhone: s.phone,
        enrolledCourse: s.enrolledCourse,
        remainingPrivateCredits: s.remainingPrivateCredits,
        remainingGroupCredits: s.remainingGroupCredits,
        totalCredits: s.remainingPrivateCredits + s.remainingGroupCredits + 8,
        remainingCredits: s.remainingPrivateCredits + s.remainingGroupCredits,
        attendanceRate: s.attendanceRate,
        averageScore: s.averageScore,
        hardestTopic: s.hardestTopic,
        meetingLink: s.meetingLink,
        isAccountGranted: s.isAccountGranted,
        assignedTeacherId: adminUser.id,
        registeredVia: 'Online Onboarding Portal',
        joinedDate: new Date(Date.now() - Math.floor(Math.random() * 90) * 86400000),
      }).onConflictDoUpdate({
        target: studentProfiles.userId,
        set: {
          parentName: s.parentName,
          parentPhone: s.parentPhone,
          schoolName: s.schoolName,
          year: s.year,
          board: s.board,
          studentPhone: s.phone,
          enrolledCourse: s.enrolledCourse,
          cohort: s.cohort,
          remainingPrivateCredits: s.remainingPrivateCredits,
          remainingGroupCredits: s.remainingGroupCredits,
          totalCredits: s.remainingPrivateCredits + s.remainingGroupCredits + 8,
          remainingCredits: s.remainingPrivateCredits + s.remainingGroupCredits,
          attendanceRate: s.attendanceRate,
          averageScore: s.averageScore,
          hardestTopic: s.hardestTopic,
          meetingLink: s.meetingLink,
          isAccountGranted: s.isAccountGranted,
        },
      });
    }
  }

  // 4. 100+ Reviews
  console.log(`⭐ Seeding ${REVIEWS_DATA.length} Reviews...`);
  // Clear existing to avoid duplicate review spam on multiple seeds
  await db.delete(reviews);
  for (let i = 0; i < REVIEWS_DATA.length; i++) {
    const rev = REVIEWS_DATA[i];
    const linkedStudent = createdStudents[i % createdStudents.length];
    await db.insert(reviews).values({
      name: rev.name,
      cohort: rev.cohort,
      rating: rev.rating,
      status: rev.status,
      content: rev.content,
      studentId: linkedStudent ? linkedStudent.id : null,
      createdAt: new Date(Date.now() - Math.floor(Math.random() * 120) * 86400000),
    });
  }

  // 5. Booking Sessions (Private & Group Masterclasses)
  console.log('📅 Seeding Group & Private Booking Sessions...');
  await db.delete(sessionStudents);
  await db.delete(bookingSessions);

  const activeStudents = createdStudents.filter((_, idx) => idx < 30);

  // A. Group Masterclass Cohorts
  const group1Date = new Date();
  group1Date.setDate(group1Date.getDate() + 2);
  group1Date.setHours(18, 0, 0, 0);

  const [groupSession1] = await db.insert(bookingSessions).values({
    teacherId: adminUser.id,
    courseName: 'Cambridge A-Level Physics (9702)',
    topic: 'Electromagnetic Induction, Faraday & Lenz Laws Live Masterclass',
    sessionFormat: 'GROUP',
    date: group1Date,
    time: '06:00 PM - 07:30 PM',
    durationMinutes: 90,
    location: 'ONLINE',
    status: 'APPROVED',
    meetingLink: 'https://meet.google.com/sayed-quantum-group',
    notes: 'Please review Faraday formula derivations and magnetic flux density definitions prior to class.',
  }).returning();

  // Attach 10 students to Group 1
  for (let i = 0; i < 10 && i < activeStudents.length; i++) {
    await db.insert(sessionStudents).values({
      sessionId: groupSession1.id,
      studentId: activeStudents[i].id,
    }).onConflictDoNothing();
  }

  const group2Date = new Date();
  group2Date.setDate(group2Date.getDate() + 4);
  group2Date.setHours(16, 0, 0, 0);

  const [groupSession2] = await db.insert(bookingSessions).values({
    teacherId: adminUser.id,
    courseName: 'Edexcel International IGCSE Physics (4PH1)',
    topic: 'Paper 4 & Paper 6 Intensive Problem Solving Workshop',
    sessionFormat: 'GROUP',
    date: group2Date,
    time: '04:00 PM - 05:30 PM',
    durationMinutes: 90,
    location: 'ONLINE',
    status: 'APPROVED',
    meetingLink: 'https://meet.google.com/sayed-igcse-alpha',
    notes: 'Bring scientific calculator, graph paper, and ruler for ATP lab questions.',
  }).returning();

  // Attach 8 students to Group 2
  for (let i = 10; i < 18 && i < activeStudents.length; i++) {
    await db.insert(sessionStudents).values({
      sessionId: groupSession2.id,
      studentId: activeStudents[i].id,
    }).onConflictDoNothing();
  }

  // B. Private 1-on-1 Sessions (Upcoming, Completed, Pending)
  const PRIVATE_TOPICS = [
    { topic: 'Circular Motion & Centripetal Acceleration Derivations', course: 'Cambridge A-Level Physics', offsetDays: 1, time: '04:00 PM - 05:00 PM', status: 'APPROVED' as const },
    { topic: 'Thermodynamics Carnot Efficiency & Heat Engines', course: 'Oxford AQA AS Physics', offsetDays: 2, time: '06:00 PM - 07:00 PM', status: 'APPROVED' as const },
    { topic: 'Photoelectric Effect & Planck Constant Calculations', course: 'Cambridge AS Physics', offsetDays: 3, time: '02:00 PM - 03:00 PM', status: 'APPROVED' as const },
    { topic: 'Hooke’s Law & Elastic Strain Energy In-Depth Review', course: 'Edexcel IGCSE Physics', offsetDays: 5, time: '07:00 PM - 08:00 PM', status: 'PENDING' as const },
    { topic: 'Simple Harmonic Motion Phase Angle & Damped Oscillations', course: 'Cambridge A2 Physics', offsetDays: 6, time: '05:00 PM - 06:00 PM', status: 'PENDING' as const },
    // Completed past sessions with rich notes
    {
      topic: 'Capacitor Charge & Discharge Exponential Equations',
      course: 'Cambridge A2 Physics',
      offsetDays: -3,
      time: '04:00 PM - 05:00 PM',
      status: 'COMPLETED' as const,
      sessionNotes: {
        title: 'Mastering Capacitance, Time Constants & Energy',
        summaryNotes: 'We derived Q = Q₀ e^(-t/RC) and V = V₀ e^(-t/RC). Focused on log-linear linearization ln(V) vs t to extract RC from experimental graph gradients. Covered discharging energy E = 1/2 CV² and dielectric permittivity.',
        keyConcepts: ['Capacitance Definition', 'Time Constant Tau = RC', 'Exponential Decay Law', 'Dielectric Constant Permittivity', 'Energy Stored in E-Field'],
        uploadedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
      },
    },
    {
      topic: 'Kirchhoff’s 1st & 2nd Laws in Multi-Loop Networks',
      course: 'Cambridge AS Physics',
      offsetDays: -5,
      time: '06:00 PM - 07:00 PM',
      status: 'COMPLETED' as const,
      sessionNotes: {
        title: 'DC Circuits & Potential Divider Masterclass',
        summaryNotes: 'Covered loop sign conventions for EMF and IR voltage drops. Worked through 6 past paper questions featuring internal resistance r and lost volts Ir. Solved LDR and thermistor sensor circuits.',
        keyConcepts: ['Conservation of Charge', 'Conservation of Energy', 'EMF vs Terminal PD', 'Internal Resistance', 'Potential Divider Ratio'],
        uploadedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
      },
    },
    {
      topic: 'Superposition, Young’s Double Slit & Diffraction Gratings',
      course: 'Cambridge AS Physics',
      offsetDays: -7,
      time: '02:00 PM - 03:00 PM',
      status: 'COMPLETED' as const,
      sessionNotes: {
        title: 'Wave Interference & Grating Equation d sin(theta) = n lambda',
        summaryNotes: 'Detailed derivations of path difference and phase difference. Compared two-source fringe spacing x = lambda*D/a with multi-slit diffraction grating maxima. Examined zero order, first order, and highest observable order.',
        keyConcepts: ['Coherent Sources', 'Path Difference Delta x = n lambda', 'Diffraction Grating Order Limit', 'Single Slit Envelope'],
        uploadedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
      },
    },
  ];

  for (let i = 0; i < activeStudents.length; i++) {
    const student = activeStudents[i];
    const topicInfo = PRIVATE_TOPICS[i % PRIVATE_TOPICS.length];
    const sessionDate = new Date();
    sessionDate.setDate(sessionDate.getDate() + topicInfo.offsetDays);
    sessionDate.setHours(16 + (i % 4), 0, 0, 0);

    await db.insert(bookingSessions).values({
      studentId: student.id,
      teacherId: adminUser.id,
      courseName: topicInfo.course,
      topic: topicInfo.topic,
      sessionFormat: 'PRIVATE',
      date: sessionDate,
      time: topicInfo.time,
      durationMinutes: 60,
      location: 'ONLINE',
      status: topicInfo.status,
      meetingLink: `https://meet.google.com/sayed-private-${student.name.toLowerCase().replace(/[^a-z]/g, '')}`,
      notes: '1-on-1 private tutoring session with Mr. Mohammed Sayed.',
      sessionNotes: (topicInfo as any).sessionNotes || null,
      creditDeducted: topicInfo.status === 'COMPLETED',
      creditTypeDeducted: topicInfo.status === 'COMPLETED' ? '1-to-1' : null,
    });
  }

  // 6. Payment Proofs & Invoices
  console.log('💳 Seeding Payment Proofs & Invoices...');
  await db.delete(paymentProofs);
  await db.delete(invoices);

  const PACKAGES = [
    { name: '10x Private 1-on-1 Masterclass Bundle', count: 10, format: '1-to-1', amount: '5400.00' },
    { name: '5x Private 1-on-1 Sessions Sprint', count: 5, format: '1-to-1', amount: '3000.00' },
    { name: 'Semester Group Cohort Pass (16 Sessions)', count: 16, format: 'group', amount: '4800.00' },
    { name: 'Monthly Group Track (8 Sessions)', count: 8, format: 'group', amount: '2400.00' },
    { name: 'Single 1-on-1 Emergency Revision Session', count: 1, format: '1-to-1', amount: '600.00' },
  ];

  const METHODS = ['InstaPay', 'Vodafone Cash', 'Bank Transfer / IBAN', 'CIB Wire / SWIFT'];

  for (let i = 0; i < 25 && i < activeStudents.length; i++) {
    const student = activeStudents[i];
    const pkg = PACKAGES[i % PACKAGES.length];
    const method = METHODS[i % METHODS.length];
    const isPending = i >= 20; // 5 pending
    const isRejected = i === 19; // 1 rejected
    const status = isRejected ? 'REJECTED' : isPending ? 'PENDING' : 'APPROVED';

    const [proof] = await db.insert(paymentProofs).values({
      studentId: student.id,
      packageName: pkg.name,
      sessionsCount: pkg.count,
      creditType: pkg.format,
      amount: pkg.amount,
      paymentMethod: method,
      senderAccountOrPhone: `010${Math.floor(10000000 + Math.random() * 90000000)}`,
      transactionRef: `TXN-${20250000 + i}`,
      screenshotUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&auto=format&fit=crop&q=60',
      submittedAt: new Date(Date.now() - (30 - i) * 86400000),
      status: status,
      reviewedBy: status !== 'PENDING' ? adminUser.id : null,
      reviewedAt: status !== 'PENDING' ? new Date() : null,
      rejectionReason: isRejected ? 'Screenshot image was blurry and transaction reference was unverified.' : null,
      notes: `Transfer for ${student.name} ${pkg.name}.`,
    }).returning();

    // Create corresponding Invoice
    const invoiceStatus = status === 'APPROVED' ? 'PAID' : status === 'PENDING' ? 'UNPAID' : 'CANCELLED';
    await db.insert(invoices).values({
      invoiceNumber: `INV-2025-${String(i + 1).padStart(3, '0')}`,
      studentId: student.id,
      parentName: `${student.name.split(' ')[0]}'s Parent`,
      packageName: pkg.name,
      amount: pkg.amount,
      issueDate: new Date(Date.now() - (35 - i) * 86400000),
      dueDate: new Date(Date.now() + (10 + i) * 86400000),
      status: invoiceStatus,
      paymentMethod: method,
      paidAt: invoiceStatus === 'PAID' ? new Date(Date.now() - (30 - i) * 86400000) : null,
      referenceNote: `Verified via ${proof.transactionRef || 'Electronic Portal'}`,
    });
  }

  // 7. Assignments & Submissions
  console.log('📝 Seeding Assignments & Submissions...');
  await db.delete(homeworkSubmissions);
  await db.delete(assignments);

  const ASSIGNMENTS_DATA = [
    {
      title: 'Electromagnetic Induction & Faraday’s Law Classified Past Papers',
      course: 'Cambridge A-Level Physics',
      module: 'Electromagnetism',
      description: 'Solve Section A & B from 2020-2024 Cambridge 9702 Paper 4 questions on magnetic flux linkage, Lenz’s law, and AC generators.',
      totalPoints: 100,
    },
    {
      title: 'Wave Superposition & Double Slit Interference Worksheet',
      course: 'Cambridge AS Physics',
      module: 'Waves & Optics',
      description: 'Calculate fringe spacing, grating orders, and sketch phase difference graphs for coherent light sources.',
      totalPoints: 50,
    },
    {
      title: 'Thermodynamics Ideal Gases & Kinetic Theory Problem Set',
      course: 'Oxford AQA A-Level Physics',
      module: 'Thermal Physics',
      description: 'Derive pV = 1/3 N m <c²> from momentum impulse and solve root-mean-square speed calculations.',
      totalPoints: 60,
    },
    {
      title: 'IGCSE Motion, Velocity-Time Graphs & Terminal Velocity Drill',
      course: 'Cambridge IGCSE Physics',
      module: 'Mechanics',
      description: 'Analyze falling parachutist graphs, calculate air resistance forces, and determine stopping distances.',
      totalPoints: 40,
    },
    {
      title: 'Nuclear Binding Energy & Radioactive Half-Life Equations',
      course: 'Edexcel International A2 Physics',
      module: 'Nuclear & Particle Physics',
      description: 'Calculate mass defects in MeV/c² and decay constants from half-life exponential equations.',
      totalPoints: 75,
    },
  ];

  for (let i = 0; i < ASSIGNMENTS_DATA.length; i++) {
    const aData = ASSIGNMENTS_DATA[i];
    const dueDate = new Date();
    dueDate.setDate(dueDate.getDate() + (7 - i * 2));

    const [assignment] = await db.insert(assignments).values({
      title: aData.title,
      course: aData.course,
      module: aData.module,
      description: aData.description,
      dueDate,
      totalPoints: aData.totalPoints,
      assignedStudentIds: activeStudents.map((s) => s.id),
      attachments: [{ name: `${aData.title.split(' ')[0]}-Worksheet.pdf`, url: 'https://example.com/worksheet.pdf' }],
    }).returning();

    // Create submissions for first 8 students
    for (let sIdx = 0; sIdx < 6 && sIdx < activeStudents.length; sIdx++) {
      const student = activeStudents[sIdx];
      const isGraded = sIdx < 4;
      const score = 80 + Math.floor(Math.random() * 20);
      const letterGrade = score >= 90 ? 'A*' : score >= 80 ? 'A' : 'B';

      await db.insert(homeworkSubmissions).values({
        assignmentId: assignment.id,
        studentId: student.id,
        submittedAt: new Date(Date.now() - (sIdx + 1) * 86400000),
        fileName: `${student.name.replace(/\s+/g, '_')}_${assignment.title.split(' ')[0]}_Solution.pdf`,
        fileSize: '2.4 MB',
        fileUrl: 'https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?w=800&auto=format&fit=crop&q=60',
        status: isGraded ? 'GRADED' : 'SUBMITTED',
        score: isGraded ? String(score) : null,
        letterGrade: isGraded ? letterGrade : null,
        feedbackNotes: isGraded ? `Excellent mathematical rigor by ${student.name}. Make sure to state vector directions and include proper SI units in final answers.` : null,
        gradedBy: isGraded ? adminUser.id : null,
        gradedAt: isGraded ? new Date() : null,
      });
    }
  }

  // 8. Support Tickets
  console.log('🎧 Seeding Support Tickets...');
  await db.delete(tickets);

  const TICKETS_DATA = [
    {
      subject: 'Question on Problem 4 in Electromagnetic Induction HW',
      category: 'Academic Question',
      priority: 'HIGH' as const,
      status: 'RESOLVED' as const,
      messages: [
        { id: '1', sender: 'Omar Tarek', role: 'student', text: 'Mr. Mohammed, in question 4, why is the induced EMF negative when the flux is increasing?', timestamp: new Date(Date.now() - 3 * 86400000).toISOString() },
        { id: '2', sender: 'Mr. Mohammed Sayed', role: 'admin', text: 'Hello Omar! By Lenz’s Law (epsilon = -dPhi/dt), the induced current creates an opposing magnetic field to resist the flux change. See page 14 in your lecture notes.', timestamp: new Date(Date.now() - 2 * 86400000).toISOString() },
      ],
    },
    {
      subject: 'Request to reschedule Sunday 1-on-1 session',
      category: 'Schedule Change',
      priority: 'MEDIUM' as const,
      status: 'OPEN' as const,
      messages: [
        { id: '1', sender: 'Mariam Mostafa', role: 'student', text: 'Hello Mr. Mohammed, could we please move our Sunday session from 4 PM to 6 PM due to a school mock exam?', timestamp: new Date(Date.now() - 86400000).toISOString() },
      ],
    },
    {
      subject: 'Confirmation of InstaPay receipt verification',
      category: 'Billing & Package',
      priority: 'LOW' as const,
      status: 'RESOLVED' as const,
      messages: [
        { id: '1', sender: 'Ziad Hassan', role: 'student', text: 'I just uploaded our transfer proof for 10 private sessions. Please confirm when credits are added.', timestamp: new Date(Date.now() - 4 * 86400000).toISOString() },
        { id: '2', sender: 'Mr. Mohammed Sayed', role: 'admin', text: 'Verified and approved! 10 private credits are now available in your portal balance.', timestamp: new Date(Date.now() - 3 * 86400000).toISOString() },
      ],
    },
    {
      subject: 'Cannot open digital whiteboard PDF notes on mobile',
      category: 'Technical Issue',
      priority: 'MEDIUM' as const,
      status: 'IN_PROGRESS' as const,
      messages: [
        { id: '1', sender: 'Farida Abdel-Aziz', role: 'student', text: 'When clicking download notes on iPhone Safari, the PDF opens as a blank page.', timestamp: new Date(Date.now() - 12 * 3600000).toISOString() },
        { id: '2', sender: 'Mr. Mohammed Sayed', role: 'admin', text: 'We are updating the direct download headers. In the meantime, I sent you the copy directly on WhatsApp.', timestamp: new Date(Date.now() - 6 * 3600000).toISOString() },
      ],
    },
  ];

  for (let i = 0; i < TICKETS_DATA.length; i++) {
    const t = TICKETS_DATA[i];
    const student = activeStudents[i % activeStudents.length];
    await db.insert(tickets).values({
      ticketNumber: `TCK-2025-${String(i + 1).padStart(3, '0')}`,
      studentId: student.id,
      requesterRole: 'student',
      subject: t.subject,
      category: t.category,
      priority: t.priority,
      status: t.status,
      messages: t.messages,
      createdAt: new Date(Date.now() - (5 - i) * 86400000),
    });
  }

  // 9. Hall of Fame
  console.log('🏆 Seeding Hall of Fame Alumni...');
  await db.delete(hallOfFame);

  const HOF_DATA = [
    {
      studentName: 'Laila Mansour',
      cohort: 'Class of 2023',
      superlativeBadge: 'Imperial College Scholar',
      quote: 'Mr. Mohammed’s mechanics problem sets made university entrance interviews at Imperial second nature.',
      admittedUniversity: 'Imperial College London',
      gradeOrScore: 'A* in A-Level Physics (99%)',
      curriculum: 'Cambridge A-Level',
      majorField: 'Mechanical Engineering (BEng)',
      mentorLetter: 'Laila consistently showed exceptional mathematical acumen and physical intuition.',
      mentorName: 'Mr. Mohammed Sayed',
      honors: 'Top in Egypt - Cambridge International Awards',
      certificateId: 'CERT-MSPA-2023-001',
    },
    {
      studentName: 'Omar Sherif',
      cohort: 'Class of 2024',
      superlativeBadge: 'Cambridge University Offer',
      quote: 'The deep derivations of electromagnetism and quantum phenomena gave me the winning edge.',
      admittedUniversity: 'University of Cambridge (Trinity College)',
      gradeOrScore: 'A* in A-Level Physics (100% P4)',
      curriculum: 'Cambridge A-Level',
      majorField: 'Natural Sciences (Physics)',
      mentorLetter: 'Omar possesses a rare intuition for theoretical physics and mathematical symmetry.',
      mentorName: 'Mr. Mohammed Sayed',
      honors: 'Outstanding Cambridge Learner Award',
      certificateId: 'CERT-MSPA-2024-002',
    },
    {
      studentName: 'Mariam El-Shenawy',
      cohort: 'Class of 2024',
      superlativeBadge: 'Edexcel National Record',
      quote: 'Scoring a 9 in IGCSE Physics gave me the confidence to pursue aerospace engineering.',
      admittedUniversity: 'University of Manchester',
      gradeOrScore: 'Grade 9 (98% Raw Score)',
      curriculum: 'Edexcel IGCSE',
      majorField: 'Aerospace Engineering',
      mentorLetter: 'Mariam’s dedication and attention to precision are unparalleled.',
      mentorName: 'Mr. Mohammed Sayed',
      honors: 'Highest Raw Score in Egypt',
      certificateId: 'CERT-MSPA-2024-003',
    },
    {
      studentName: 'Karim Abdel-Meguid',
      cohort: 'Class of 2023',
      superlativeBadge: 'TU Munich Scholar',
      quote: 'The foundational electrical circuit analysis and thermodynamics served as my engineering backbone.',
      admittedUniversity: 'Technical University of Munich (TUM)',
      gradeOrScore: 'A* in A-Level Physics',
      curriculum: 'Edexcel IAL',
      majorField: 'Electrical & Computer Engineering',
      mentorLetter: 'Karim is a born problem solver with an exceptional engineering mindset.',
      mentorName: 'Mr. Mohammed Sayed',
      honors: 'Distinction in Applied Physics',
      certificateId: 'CERT-MSPA-2023-004',
    },
    {
      studentName: 'Salma Khaled',
      cohort: 'Class of 2024',
      superlativeBadge: 'Oxford AQA Top in Region',
      quote: 'Thermodynamics and wave mechanics were taught with absolute passion and clarity.',
      admittedUniversity: 'University College London (UCL)',
      gradeOrScore: 'A* in A-Level Physics',
      curriculum: 'Oxford AQA',
      majorField: 'Biomedical Physics',
      mentorLetter: 'Salma’s analytical approach to complex experimental problems set her apart.',
      mentorName: 'Mr. Mohammed Sayed',
      honors: 'Oxford AQA Certificate of Excellence',
      certificateId: 'CERT-MSPA-2024-005',
    },
  ];

  for (const h of HOF_DATA) {
    await db.insert(hallOfFame).values({
      ...h,
      graduationDate: new Date('2024-06-30'),
    });
  }

  // 10. Academic Resources
  console.log('📚 Seeding Academic Resources Library...');
  await db.delete(resources);

  const RESOURCES_DATA = [
    {
      title: 'Complete A-Level Physics Formula Sheet & Derivation Guide (9702)',
      category: 'Formula Sheet',
      course: 'Cambridge A-Level Physics',
      topic: 'Comprehensive All Modules',
      fileFormat: 'PDF',
      fileSize: '3.8 MB',
      downloadCount: 342,
      author: 'Mr. Mohammed Sayed',
      description: 'Comprehensive formula derivations with SI unit breakdowns and common exam pitfalls highlighted.',
      badge: 'Essential',
    },
    {
      title: 'Electromagnetic Induction & Faraday’s Law Classified Booklet (2015-2024)',
      category: 'Lecture Notes',
      course: 'Cambridge A-Level Physics',
      topic: 'Electromagnetism',
      fileFormat: 'PDF',
      fileSize: '8.2 MB',
      downloadCount: 512,
      author: 'Mr. Mohammed Sayed',
      description: 'Topical past paper compilation classified by question type with mark scheme solutions.',
      badge: 'High Yield',
    },
    {
      title: 'Paper 6 Alternative to Practical (ATP) Full Lab Manual',
      category: 'Lab Manual',
      course: 'Cambridge IGCSE Physics (0625)',
      topic: 'Experimental Physics',
      fileFormat: 'PDF',
      fileSize: '5.1 MB',
      downloadCount: 689,
      author: 'Mr. Mohammed Sayed',
      description: 'Step-by-step apparatus setups, uncertainty propagation, graph plotting rules, and standard precautions.',
      badge: 'Top Rated',
    },
    {
      title: 'Quantum Physics & Nuclear Structure Cheat Sheet',
      category: 'Formula Sheet',
      course: 'Edexcel International A2 Physics',
      topic: 'Quantum & Nuclear',
      fileFormat: 'PDF',
      fileSize: '2.4 MB',
      downloadCount: 275,
      author: 'Mr. Mohammed Sayed',
      description: 'Photoelectric effect, de Broglie wavelength, binding energy curve, and half-life formulas.',
      badge: 'Updated',
    },
    {
      title: 'Mechanics & Dynamics Past Paper 4 Worked Solutions Video Masterclass',
      category: 'Video Masterclass',
      course: 'Cambridge AS Physics',
      topic: 'Mechanics',
      fileFormat: 'MP4',
      fileSize: '180 MB',
      downloadCount: 420,
      author: 'Mr. Mohammed Sayed',
      description: 'Full 90-minute walkthrough solving projectile motion, momentum in 2D, and equilibrium questions.',
      badge: 'Video',
    },
  ];

  for (const r of RESOURCES_DATA) {
    await db.insert(resources).values({
      ...r,
      fileUrl: 'https://example.com/resources/' + r.title.toLowerCase().replace(/[^a-z0-9]/g, '-') + '.pdf',
    });
  }

  console.log('✅ Full realistic seed completed successfully!');
  console.log('───────────────────────────────────────────────────────');
  console.log(`👨‍🏫 Admin credentials: ${adminUser.email} / (Password: ${process.env.SEED_ADMIN_PASSWORD || 'change-me-admin'})`);
  console.log(`👨‍🎓 Demo Student: student@example.com / (Password: ${process.env.SEED_STUDENT_PASSWORD || 'password123'})`);
  console.log(`⭐ Total Reviews Seeded: ${REVIEWS_DATA.length}`);
  console.log(`👥 Total Scholars Seeded: ${STUDENTS_DATA.length}`);
  console.log('───────────────────────────────────────────────────────');
};

runFullSeed().catch((err) => {
  console.error('❌ Seed execution failed:', err);
  process.exit(1);
});